 
swagger: '2.0'
info:
  description:  |
    Bienvenido a la API de [Multicaja](https://www.multicaja.cl) (Alpha)
    ** Este es un proyecto alpha  **
    Todos los requests son autenticados usando un `api-key`.
  version: "1.0.0"
  title: API Multicaja de Pasarela
  # put the contact info for your development or API team
  contact:
    email: matias.salinas@multicaja.cl
    

consumes:
  - application/json
produces:
  - application/json
  
# tags are used for organizing operations
tags:
- name: transaccional
  description: Opciones de la  Orden
- name: general
  description: Información transversal de todos los medios de pago

paths:
  /pdp/v1.0/orders:
    post:
      tags:
      - transaccional
      summary: Generar una order (Intención de pago)
      description: |
        Servicio para poder crear una intención de pago.
        Los campos obligatorios son : 
        
          * **reference_id** : Es el **ID** interno del comercio.
          * **amount** : Datos del monto.
          * **description** : Descripción de orden.
          * **urls** : Url de redirección para los casos de éxito y error.
        
        Los campos :
          * **methods** : Lista de medios de pago habilitados ´["paypal","tarjetas","transferencia","efectivo"]´
          
          * **items** : El campo item list contiene la siguiente lista de objetos los cuales pertenecen al detalle de la operación.
          
            * **{ 
              name : string,
              code : string,
              price : number,
              quantity : number
            }** 
          
          * **customs**  : 
            El campo item list contiene la siguiente lista de key/value los cuales son utiles en el caso de ocupar un webhook.
            
            * **{ 
              string : string
            } **
          
          * **urls** : Son las url de retorno en caso de que la operación se relice con éxito o error.
      parameters:
      - in: body
        required: true
        name: body
        description: Parametros de entrada para el comercio
        schema:
          $ref: '#/definitions/ordersModel'
      consumes:
      - application/json    
      produces:
      - application/json
      responses:
        201:
          description: Orden creada con éxito
          schema:
            $ref: '#/definitions/orderModelResponse'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorModel'
  /pdp/v1.0/orders/{order_id}:
    get:
      tags:
      - transaccional
      description: |
        Servicio para poder obtener detalles de la orden y su estado actual
      summary: Obtener el estado de la orden
      operationId: addInventory
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: order_id
          description: ID de orden de boton de pago
          required: true
          type: number
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/orderModelResponse'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorModel'
        403:
          description: La orden fue anulada.
          schema:
            $ref: '#/definitions/ErrorModel'
        404:
          description: error obtención de datos
    put:
      tags:
      - transaccional
      summary: Actualizar la orden
      description: |
        Servicio para actualizar orden, permite actualizar los siguientes campos :  
        
          * **reference_id** : Es el **ID** interno del comercio.
          * **description** : Descripción de orden.
          * **items** : El campo item list contiene la siguiente lista de objetos los cuales pertenecen al detalle de la operación.
          
            * **{ 
              name : string,
              code : string,
              price : string,
              quantity : string
            }** 
          
          * **custom_values**  : 
            El campo item list contiene la siguiente lista de key/value los cuales son utiles en el caso de ocupar un webhook.
            
            * **{ 
              string : string
            }** 
            
          
          * **urls** : Son las url de retorno en caso de que la operación se relice con éxito o error.
          
          
          **NOTA:** Esta operación solo esta permitida con ordenes pendientes de pago.
          
      parameters:
        - in: path
          name: order_id
          description: ID de orden
          required: true
          type: number
        - in: body
          required: true
          name: body
          description: Parametros de entrada para el comercio
          schema:
            $ref: '#/definitions/ordersModel'
      consumes:
      - application/json    
      produces:
      - application/json
      responses:
        201:
          description: Orden creada con éxito
          schema:
            $ref: '#/definitions/orderModelResponse'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorModel'
      
    delete:
      tags:
      - transaccional
      summary: Cancelar la orden
      description: |
        Este servicio permite anular orden.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: order_id
          description: id de orden de boton de pago
          required: true
          type: number
      responses:
        200:
          description: ok
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorModel'
        410:
          description: La intención de pago fue anulada.
          schema:
            $ref: '#/definitions/ErrorModel'
        404:
          description: error orden no existe
 
  /pdp/v1.0/general/paymentmethods:
    get:
      tags:
      - general
      summary: Obtener lista de medios de pago
      description: |
        Muestra una lista de medios de pago.
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/paymentMethodItemObject'  
        410:
          description: La orden fue anulada.
          schema:
            $ref: '#/definitions/ErrorModel' 
        
  
definitions:

  ordersModel:
    type: object
    required:
    - reference_id
    - amount
    - description
    - payments
    properties:
      reference_id:
        type: string
        example: "ERWER213"
      amount:
        $ref: '#/definitions/amountModel'
      methods:
        type: array
        example: ['paypal', 'tarjetas', 'transferencia', 'efectivo']
        items:
          type: string
          example: "paypal"
      items:
        type: array
        items:
          $ref: '#/definitions/itemModel'
      description:
        type: string
        example: Esta es una orden
      customs:
        type: array
        items:
          $ref: '#/definitions/customModel'
      urls:
        $ref: '#/definitions/urlModel'

  orderModelResponse:
    allOf:
      - $ref: '#/definitions/ordersModel'
      - properties:
          status:
            type: string
            enum: ['pending', 'canceled', 'completed','expired']
            example: "pending"
          order_id:
            type: number
            example: 645646
          redirect_url:
            type: string
            example: 'http://pagos.multicaja.cl/url_retorno'
          history:
            type: array
            items:
              $ref: '#/definitions/historyModel'
  amountModel:
    type: object
    properties:
      currency:
        type: string
        example: "CLP"
      total:
        type: number
        example: 41000
      details:
        type: object
        properties:
          subtotal:
            type: number
            example: 39000
          commission:
            type: number
            example: 1000
          tax:
            type: number
            example: 1000
            
  customModel:
    type: object
    properties:
      key:
        type: string
        example: "value"

  itemModel: 
    properties:
      name:
        type: string
        example: "name"
      code:
        type: string
        example: "name"
      price:
        type: number
        example: 39000
      unit_price:
        type: number
        example: 13000
      quantity:
        type: number
        example: 3

  historyModel:
    type: object
    description: Parámetro básico **(Response)**
    properties:
      id:
        type: integer
        description: identificador de la operación
        example: 132312213
      name:
        type: string
        enum: ["payment","cancellation","expiration","other","crated"]
        description: Tipo de operación
        example: "crated"
      description:
        type: string
        description: Descripcion de la operación
        example: "Orden fue creada con exito"
      total_operation:
        type: number
        description: Monto de la operación  (Opcional)
        example: 41000
      date:
        type: string
        format: date-time
        example: "2018-01-14T15:27:42.669Z"
      status:
        type: string
        enum: ["approved","rejected"]
        description: Tipo de operación
        example: "approved"
        
  urlModel:
    required:
      - return_url 
      - cancel_url
    properties:
      return_url:
          type: string
          example: "http://multicaja.cl/return_url"
      cancel_url:
          type: string
          example: "http://multicaja.cl/cancel_url"
          
  paymentMethodItemObject:
    type: object
    properties:
      payment_method:
        type: string
        example: 'paypal'
      payment_max_amount:
        type: number
        example: 40000
        
  ErrorModel:
    type: object
    properties:
      code: 
        type: string
        example: INVALID_DATA
        description: Variable de error
      message:
        type: string
        example: Invalid property '{property_name}'.
        description: Descripción del error
    
